# Generated by Django 3.2.7 on 2021-09-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210919_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=155, primary_key=True, serialize=False),
        ),
    ]
