# Generated by Django 3.2.7 on 2021-09-19 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('organization', models.CharField(max_length=50)),
                ('poster', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
