# Generated by Django 3.2.7 on 2021-09-19 11:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='poster',
        ),
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='website.profile'),
            preserve_default=False,
        ),
    ]
